## Section 0: Imports and Setup

Run this section first. It contains all notebook imports, project paths, and reusable helper imports used by the later sections.

In [19]:
import importlib
import os
import socket
import sys
from datetime import date
from pathlib import Path

import pandas as pd
import polars as pl
import plotly.express as px
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.dialects import registry as _sa_registry

try:
    import ibm_db
    import ibm_db_dbi
    import ibm_db_sa
    DB2_DRIVER_READY = True
    DB2_DRIVER_ERROR = None
except Exception as exc:
    ibm_db = None
    ibm_db_dbi = None
    ibm_db_sa = None
    DB2_DRIVER_READY = False
    DB2_DRIVER_ERROR = exc
    print(f"DB2 driver is not ready: {type(exc).__name__}: {exc}")

_sa_registry.register("db2", "ibm_db_sa.ibm_db", "DB2Dialect_ibm_db")
_sa_registry.register("db2.ibm_db", "ibm_db_sa.ibm_db", "DB2Dialect_ibm_db")

load_dotenv()

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
OUTPUT_DIR = PROJECT_ROOT / "data" / "output"
for directory in (RAW_DIR, PROCESSED_DIR, OUTPUT_DIR):
    directory.mkdir(parents=True, exist_ok=True)

import src.data_clean as data_clean
import src.data_enrich as data_enrich
import src.data_inspect as data_inspect
import src.data_model as data_model
from src.pull_data import TABLES, pull_and_save

importlib.reload(data_clean)
importlib.reload(data_enrich)
importlib.reload(data_inspect)
importlib.reload(data_model)

from src.data_clean import clean_raw_tables
from src.data_enrich import enrich_tables
from src.data_model import (
    check_flight_dashboard_joins,
    make_flight_dashboard_table,
)
from src.data_inspect import (
    RAW_TABLES,
    check_raw_files,
    load_tables,
    missing_value_counts,
    summary_statistics,
)

TABLE_NAMES = list(RAW_TABLES)

print(f"Polars version: {pl.__version__}")
print(f"Project root: {PROJECT_ROOT}")
print(f"Raw data: {RAW_DIR}")
print(f"Processed data: {PROCESSED_DIR}")

Polars version: 1.41.2
Project root: c:\Users\rothl\Desktop\ATT Group Project\ATT-Group8
Raw data: c:\Users\rothl\Desktop\ATT Group Project\ATT-Group8\data\raw
Processed data: c:\Users\rothl\Desktop\ATT Group Project\ATT-Group8\data\processed

In [20]:
DB_HOST = os.getenv("DB_HOST", "52.211.123.34")
DB_PORT = int(os.getenv("DB_PORT", "25010"))
DB_NAME = os.getenv("DB_NAME", "ATTPLANE")
DB_USERNAME = os.getenv("DB_USERNAME", "attgrp8")   # ← change to your group number
DB_PASSWORD = os.getenv("DB_PASSWORD", "bigdata")

print({"host": DB_HOST, "port": DB_PORT, "database": DB_NAME, "username": DB_USERNAME, "password": "***"})

{'host': '52.211.123.34', 'port': 25010, 'database': 'ATTPLANE', 'username': 'attgrp8', 'password': '***'}

In [21]:
def tcp_check(host: str = DB_HOST, port: int = DB_PORT, timeout: float = 8.0) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(timeout)
        sock.connect((host, port))
    return True

try:
    tcp_check()
    print(f"TCP connection succeeded: {DB_HOST}:{DB_PORT} is reachable")
except Exception as exc:
    print(f"TCP connection failed: {type(exc).__name__}: {exc}")

TCP connection succeeded: 52.211.123.34:25010 is reachable

In [22]:
def _make_raw_connection():
    if not DB2_DRIVER_READY:
        raise RuntimeError("DB2 driver is not ready") from DB2_DRIVER_ERROR

    conn_str = (
        f"HOSTNAME={DB_HOST};PORT={DB_PORT};DATABASE={DB_NAME};"
        f"PROTOCOL=TCPIP;UID={DB_USERNAME};PWD={DB_PASSWORD};"
        f"AUTHENTICATION=SERVER;CURRENTSCHEMA={DB_USERNAME.upper()};"
    )
    return ibm_db_dbi.Connection(ibm_db.connect(conn_str, "", ""))

def make_db2_engine():
    return create_engine("ibm_db_sa://", creator=_make_raw_connection)

engine = make_db2_engine()
engine

Engine(ibm_db_sa://)

In [23]:
def test_db_connection(engine) -> bool:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT 1 AS ok FROM SYSIBM.SYSDUMMY1"))
        row = result.fetchone()
    return row is not None and row[0] == 1

try:
    assert test_db_connection(engine)
    print("DB2 connection successful")
except Exception as exc:
    print("DB2 connection failed")
    print(f"{type(exc).__name__}: {exc}")
    print("\nChecklist:")
    print("1. Did the TCP check succeed?")
    print("2. Are ibm_db and ibm_db_sa installed in this notebook kernel?")
    print("3. Are DB_USERNAME and DB_PASSWORD correct for your group?")
    print("4. Is DB_NAME exactly ATTPLANE?")

DB2 connection successful

## Task 2: Data Loading

This section checks the raw parquet files in `data/raw/`. If files are missing, you can pull them from DB2 with `src.pull_data`, but the cleaning work below can use any raw files that are already present.

### 2.1 Pull Data From DB2 Using `src.pull_data`

This is the notebook hook into the existing data-pulling module. It calls `pull_and_save()` from `src/pull_data.py` and writes raw parquet files into `data/raw/`.

Leave `PULL_FROM_DB2 = False` for normal notebook runs. Change it to `True` only when you intentionally want to connect to DB2 and download missing raw files.

In [24]:
PULL_FROM_DB2 = False

if PULL_FROM_DB2:
    pulled_paths = pull_and_save(output_dir=RAW_DIR)
    pull_summary = pl.DataFrame(
        [
            {"table": table.lower(), "path": str(path)}
            for table, path in pulled_paths.items()
        ]
    )
else:
    pull_summary = pl.DataFrame(
        [
            {"table": table, "path": "not pulled in this run"}
            for table in TABLE_NAMES
        ]
    )

pull_summary

shape: (6, 2)
┌────────────┬────────────────────────┐
│ table      ┆ path                   │
│ ---        ┆ ---                    │
│ str        ┆ str                    │
╞════════════╪════════════════════════╡
│ airplanes  ┆ not pulled in this run │
│ airports   ┆ not pulled in this run │
│ flights    ┆ not pulled in this run │
│ passengers ┆ not pulled in this run │
│ routes     ┆ not pulled in this run │
│ tickets    ┆ not pulled in this run │
└────────────┴────────────────────────┘

In [25]:
print(f"Raw data folder: {RAW_DIR}")
print(f"Expected tables: {', '.join(TABLE_NAMES)}")

Raw data folder: c:\Users\rothl\Desktop\ATT Group Project\ATT-Group8\data\raw
Expected tables: airplanes, airports, flights, passengers, routes, tickets

In [26]:
raw_status = check_raw_files(raw_dir=RAW_DIR, table_names=RAW_TABLES)
raw_status

shape: (6, 5)
┌────────────┬──────────────┬─────────┬─────────┬─────────────────────────────────┐
│ table      ┆ status       ┆ rows    ┆ columns ┆ issue                           │
│ ---        ┆ ---          ┆ ---     ┆ ---     ┆ ---                             │
│ str        ┆ str          ┆ i64     ┆ i64     ┆ str                             │
╞════════════╪══════════════╪═════════╪═════════╪═════════════════════════════════╡
│ airplanes  ┆ ok           ┆ 796     ┆ 13      ┆ null                            │
│ airports   ┆ ok           ┆ 30      ┆ 9       ┆ null                            │
│ flights    ┆ ok           ┆ 1758638 ┆ 10      ┆ null                            │
│ passengers ┆ ok           ┆ 500000  ┆ 11      ┆ null                            │
│ routes     ┆ ok           ┆ 624     ┆ 7       ┆ null                            │
│ tickets    ┆ needs_repull ┆ null    ┆ null    ┆ ComputeError: parquet: File ou… │
└────────────┴──────────────┴─────────┴─────────┴─────────────────────────────────┘

## Task 3: Inspect and Clean Raw Data

This section keeps inspection simple: first display the raw tables, then show summary statistics, then count null/missing values. Cleaning happens after that.

### 3.1 Raw Tables

Check which raw parquet files can be read. Then load a sample of each readable table and display the first few rows.

In [27]:
raw_file_health = check_raw_files(raw_dir=RAW_DIR, table_names=RAW_TABLES)
raw_file_health

shape: (6, 5)
┌────────────┬──────────────┬─────────┬─────────┬─────────────────────────────────┐
│ table      ┆ status       ┆ rows    ┆ columns ┆ issue                           │
│ ---        ┆ ---          ┆ ---     ┆ ---     ┆ ---                             │
│ str        ┆ str          ┆ i64     ┆ i64     ┆ str                             │
╞════════════╪══════════════╪═════════╪═════════╪═════════════════════════════════╡
│ airplanes  ┆ ok           ┆ 796     ┆ 13      ┆ null                            │
│ airports   ┆ ok           ┆ 30      ┆ 9       ┆ null                            │
│ flights    ┆ ok           ┆ 1758638 ┆ 10      ┆ null                            │
│ passengers ┆ ok           ┆ 500000  ┆ 11      ┆ null                            │
│ routes     ┆ ok           ┆ 624     ┆ 7       ┆ null                            │
│ tickets    ┆ needs_repull ┆ null    ┆ null    ┆ ComputeError: parquet: File ou… │
└────────────┴──────────────┴─────────┴─────────┴─────────────────────────────────┘

In [28]:
raw_tables = load_tables(
    data_dir=RAW_DIR,
    table_names=RAW_TABLES,
    sample_rows=10_000,
    skip_errors=True,
)

for table_name, df in raw_tables.items():
    print(f"{table_name}: showing 5 rows from {df.height:,} loaded rows")
    display(df.head(5))

Skipping tickets: ComputeError: parquet: File out of specification: The file must end with PAR1
airplanes: showing 5 rows from 796 loaded rows

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ aircraft_ ┆ model     ┆ seats_bus ┆ seats_pre ┆ … ┆ maintenan ┆ maintenan ┆ maintenan ┆ total_fl │
│ registrat ┆ ---       ┆ iness     ┆ mium      ┆   ┆ ce_last_b ┆ ce_takeof ┆ ce_flight ┆ ight_dis │
│ ion       ┆ str       ┆ ---       ┆ ---       ┆   ┆ check     ┆ fs        ┆ _hours    ┆ tance    │
│ ---       ┆           ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ date      ┆ i64       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IE53571   ┆ BOMBARDIE ┆ null      ┆ null      ┆ … ┆ 2024-05-2 ┆ 410       ┆ 2487      ┆ 931628   │
│           ┆ R         ┆           ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│           ┆ CRJ-1000  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IE53730   ┆ BOMBARDIE ┆ 90.0      ┆ null      ┆ … ┆ 2024-04-0 ┆ 467       ┆ 2914      ┆ 555855   │
│           ┆ R CRJ-900 ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ IE53994   ┆ AIRBUS    ┆ null      ┆ null      ┆ … ┆ 2024-03-3 ┆ 213       ┆ 1834      ┆ 909017   │
│           ┆ A321-200( ┆           ┆           ┆   ┆ 1         ┆           ┆           ┆          │
│           ┆ 321)      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IE54017   ┆ AIRBUS    ┆ 31.0      ┆ 24.0      ┆ … ┆ 2024-03-1 ┆ 623       ┆ 594       ┆ 37905    │
│           ┆ A350-900( ┆           ┆           ┆   ┆ 0         ┆           ┆           ┆          │
│           ┆ 359)      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IE54199   ┆ AIRBUS    ┆ null      ┆ 21.0      ┆ … ┆ 2024-05-2 ┆ 392       ┆ 2030      ┆ 819120   │
│           ┆ A330-200( ┆           ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│           ┆ 332)      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

airports: showing 5 rows from 30 loaded rows

shape: (5, 9)
┌───────────┬────────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ iata_code ┆ airport    ┆ city      ┆ country   ┆ … ┆ timezone ┆ latitude ┆ longitude ┆ airport_t │
│ ---       ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ax        │
│ str       ┆ str        ┆ str       ┆ str       ┆   ┆ str      ┆ f64      ┆ f64       ┆ ---       │
│           ┆            ┆           ┆           ┆   ┆          ┆          ┆           ┆ f64       │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ ADJ       ┆ Amman-Mark ┆ Amman     ┆ JORDAN    ┆ … ┆ CUT+2    ┆ 31.9727  ┆ 35.9916   ┆ 9.65      │
│           ┆ a Internat ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│           ┆ ional      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│           ┆ Airp…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ ATL       ┆ Hartsfield ┆ Atlanta   ┆ UNITED    ┆ … ┆ CUT-5    ┆ 33.6367  ┆ -84.42810 ┆ 0.82      │
│           ┆ Jackson    ┆           ┆ STATES    ┆   ┆          ┆          ┆ 1         ┆           │
│           ┆ Atlanta    ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ BCN       ┆ Barcelona  ┆ Barcelona ┆ SPAIN     ┆ … ┆ CUT+1    ┆ 41.2971  ┆ 2.07846   ┆ 11.79     │
│           ┆ Internatio ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│           ┆ nal        ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│           ┆ Airpor…    ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ BLQ       ┆ Bologna    ┆ Bologna   ┆ ITALY     ┆ … ┆ CUT+1    ┆ 44.5354  ┆ 11.2887   ┆ null      │
│           ┆ Guglielmo  ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│           ┆ Marconi    ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│           ┆ Airp…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ BOG       ┆ El Dorado  ┆ Bogota    ┆ COLOMBIA  ┆ … ┆ CUT+2    ┆ 4.70159  ┆ -74.1469  ┆ null      │
│           ┆ Internatio ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│           ┆ nal        ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│           ┆ Airpor…    ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
└───────────┴────────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

flights: showing 5 rows from 10,000 loaded rows

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ flight_id ┆ flight_le ┆ frequency ┆ route_cod ┆ … ┆ airplane ┆ price_eco ┆ price_pre ┆ price_bus │
│ ---       ┆ g         ┆ ---       ┆ e         ┆   ┆ ---      ┆ nomy      ┆ mium      ┆ iness     │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ str      ┆ ---       ┆ ---       ┆ ---       │
│           ┆ i64       ┆           ┆ str       ┆   ┆          ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ IE06307  ┆ 41.68     ┆ 57.71     ┆ 84.18     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ IE06307  ┆ 42.34     ┆ 60.03     ┆ 79.44     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ IE06307  ┆ 50.94     ┆ 66.36     ┆ 85.46     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ IE06307  ┆ 40.24     ┆ 69.92     ┆ 80.55     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ IE06307  ┆ 51.32     ┆ 63.59     ┆ 76.14     │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

passengers: showing 5 rows from 10,000 loaded rows

shape: (5, 11)
┌─────┬──────────┬─────────┬──────────┬───┬───────────────┬────────────┬───────────┬───────────────┐
│ id  ┆ firstnme ┆ midinit ┆ lastname ┆ … ┆ country       ┆ vipcard    ┆ phone     ┆ email         │
│ --- ┆ ---      ┆ ---     ┆ ---      ┆   ┆ ---           ┆ ---        ┆ ---       ┆ ---           │
│ i64 ┆ str      ┆ str     ┆ str      ┆   ┆ str           ┆ str        ┆ str       ┆ str           │
╞═════╪══════════╪═════════╪══════════╪═══╪═══════════════╪════════════╪═══════════╪═══════════════╡
│ 1   ┆ Ivanna   ┆ N       ┆ Barrow   ┆ … ┆ JORDAN        ┆ null       ┆ 931916171 ┆ null          │
│ 2   ┆ Cecelia  ┆ L       ┆ Yeomans  ┆ … ┆ UNITED STATES ┆ null       ┆ null      ┆ cecelia.yeoma │
│     ┆          ┆         ┆          ┆   ┆               ┆            ┆           ┆ ns@gmail.com  │
│ 3   ┆ Mila     ┆         ┆ Stafford ┆ … ┆ SPAIN         ┆ null       ┆ null      ┆ mila.stafford │
│     ┆          ┆         ┆          ┆   ┆               ┆            ┆           ┆ @gmail.com    │
│ 4   ┆ Zane     ┆         ┆ Piper    ┆ … ┆ SPAIN         ┆ null       ┆ 281717284 ┆ zane.piper@gm │
│     ┆          ┆         ┆          ┆   ┆               ┆            ┆           ┆ ail.com       │
│ 5   ┆ Colton   ┆ O       ┆ Yeates   ┆ … ┆ SPAIN         ┆ VIP-847006 ┆ null      ┆ colton.yeates │
│     ┆          ┆         ┆          ┆   ┆               ┆            ┆           ┆ @gmail.com    │
└─────┴──────────┴─────────┴──────────┴───┴───────────────┴────────────┴───────────┴───────────────┘

routes: showing 5 rows from 624 loaded rows

shape: (5, 7)
┌────────────┬────────┬─────────────┬──────────────┬────────────┬──────────┬────────────────┐
│ route_code ┆ origin ┆ destination ┆ parent_route ┆ leg_number ┆ distance ┆ flight_minutes │
│ ---        ┆ ---    ┆ ---         ┆ ---          ┆ ---        ┆ ---      ┆ ---            │
│ str        ┆ str    ┆ str         ┆ str          ┆ i64        ┆ i64      ┆ i64            │
╞════════════╪════════╪═════════════╪══════════════╪════════════╪══════════╪════════════════╡
│ R001       ┆ JFK    ┆ TPA         ┆ R001         ┆ 0          ┆ 1621     ┆ 135            │
│ R002       ┆ TPA    ┆ ATL         ┆ R001         ┆ 1          ┆ 655      ┆ 66             │
│ R003       ┆ ATL    ┆ JFK         ┆ R001         ┆ 2          ┆ 1223     ┆ 107            │
│ R004       ┆ JFK    ┆ LAS         ┆ R004         ┆ 0          ┆ 3613     ┆ 278            │
│ R005       ┆ LAS    ┆ ATL         ┆ R004         ┆ 1          ┆ 2807     ┆ 220            │
└────────────┴────────┴─────────────┴──────────────┴────────────┴──────────┴────────────────┘

### 3.2 Summary Statistics

Show simple numeric statistics for each readable raw table.

In [29]:
raw_summary_statistics = summary_statistics(raw_tables)
raw_summary_statistics

shape: (19, 6)
┌────────────┬──────────────────────────┬───────┬─────────────┬────────┬──────────┐
│ table      ┆ column                   ┆ min   ┆ mean        ┆ median ┆ max      │
│ ---        ┆ ---                      ┆ ---   ┆ ---         ┆ ---    ┆ ---      │
│ str        ┆ str                      ┆ f64   ┆ f64         ┆ f64    ┆ f64      │
╞════════════╪══════════════════════════╪═══════╪═════════════╪════════╪══════════╡
│ airplanes  ┆ crew_members             ┆ 4.0   ┆ 10.507538   ┆ 12.0   ┆ 15.0     │
│ airplanes  ┆ fuel_gallons_hour        ┆ 222.0 ┆ 375.295226  ┆ 386.0  ┆ 540.0    │
│ airplanes  ┆ maintenance_flight_hours ┆ 5.0   ┆ 1493.090452 ┆ 1484.0 ┆ 2993.0   │
│ airplanes  ┆ maintenance_takeoffs     ┆ 0.0   ┆ 495.664573  ┆ 494.5  ┆ 999.0    │
│ airplanes  ┆ seats_business           ┆ 16.0  ┆ 34.146199   ┆ 31.0   ┆ 90.0     │
│ …          ┆ …                        ┆ …     ┆ …           ┆ …      ┆ …        │
│ flights    ┆ price_premium            ┆ 26.42 ┆ 82.118466   ┆ 84.025 ┆ 166.11   │
│ passengers ┆ id                       ┆ 1.0   ┆ 5203.3445   ┆ 5000.5 ┆ 299777.0 │
│ routes     ┆ distance                 ┆ 176.0 ┆ 6549.858974 ┆ 7633.0 ┆ 19348.0  │
│ routes     ┆ flight_minutes           ┆ 32.0  ┆ 487.407051  ┆ 565.0  ┆ 1402.0   │
│ routes     ┆ leg_number               ┆ 0.0   ┆ 0.701923    ┆ 1.0    ┆ 6.0      │
└────────────┴──────────────────────────┴───────┴─────────────┴────────┴──────────┘

### 3.3 Null and Missing Value Counts

For this notebook, missing values means Polars nulls plus blank strings in text columns.

In [30]:
raw_missing_values = missing_value_counts(raw_tables)
raw_missing_values

shape: (50, 8)
┌───────────┬──────────────┬─────────┬──────┬────────────┬─────────────┬─────────────┬─────────────┐
│ table     ┆ column       ┆ dtype   ┆ rows ┆ null_count ┆ blank_strin ┆ missing_cou ┆ missing_pct │
│ ---       ┆ ---          ┆ ---     ┆ ---  ┆ ---        ┆ g_count     ┆ nt          ┆ ---         │
│ str       ┆ str          ┆ str     ┆ i64  ┆ i64        ┆ ---         ┆ ---         ┆ f64         │
│           ┆              ┆         ┆      ┆            ┆ i64         ┆ i64         ┆             │
╞═══════════╪══════════════╪═════════╪══════╪════════════╪═════════════╪═════════════╪═════════════╡
│ airplanes ┆ seats_premiu ┆ Float64 ┆ 796  ┆ 469        ┆ 0           ┆ 469         ┆ 0.589196    │
│           ┆ m            ┆         ┆      ┆            ┆             ┆             ┆             │
│ airplanes ┆ seats_busine ┆ Float64 ┆ 796  ┆ 112        ┆ 0           ┆ 112         ┆ 0.140704    │
│           ┆ ss           ┆         ┆      ┆            ┆             ┆             ┆             │
│ airplanes ┆ seats_econom ┆ Float64 ┆ 796  ┆ 70         ┆ 0           ┆ 70          ┆ 0.08794     │
│           ┆ y            ┆         ┆      ┆            ┆             ┆             ┆             │
│ airplanes ┆ aircraft_reg ┆ String  ┆ 796  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0         │
│           ┆ istration    ┆         ┆      ┆            ┆             ┆             ┆             │
│ airplanes ┆ build_date   ┆ Date    ┆ 796  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0         │
│ …         ┆ …            ┆ …       ┆ …    ┆ …          ┆ …           ┆ …           ┆ …           │
│ routes    ┆ flight_minut ┆ Int64   ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0         │
│           ┆ es           ┆         ┆      ┆            ┆             ┆             ┆             │
│ routes    ┆ leg_number   ┆ Int64   ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0         │
│ routes    ┆ origin       ┆ String  ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0         │
│ routes    ┆ parent_route ┆ String  ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0         │
│ routes    ┆ route_code   ┆ String  ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0         │
└───────────┴──────────────┴─────────┴──────┴────────────┴─────────────┴─────────────┴─────────────┘

### 3.4 Cleaning Rules

The cleaning module is intentionally small. It applies simple rules:

- keep the original column names
- trim text columns
- turn blanks and placeholders like `NA`, `N/A`, and `NULL` into real nulls
- parse dates only when you pass date columns to the function
- remove rows that are exact duplicates

The module itself does not hardcode ATTPLANE table names or column names. In the notebook cell below, we pass the date columns we want parsed before enrichment.

In [31]:
date_columns_by_table = {
    "airplanes": (
        "build_date",
        "maintenance_last_acheck",
        "maintenance_last_bcheck",
    ),
    "passengers": ("birth_date",),
}

datetime_columns_by_table = {
    "flights": ("departure", "arrival"),
    "tickets": ("departure",),
}

cleaned_tables = clean_raw_tables(
    raw_dir=RAW_DIR,
    output_dir=PROCESSED_DIR,
    date_columns_by_table=date_columns_by_table,
    datetime_columns_by_table=datetime_columns_by_table,
    skip_errors=True,
)

processed_summary = pl.DataFrame(
    [
        {
            "table": table_name,
            "rows": df.height,
            "columns": df.width,
            "processed_path": str(PROCESSED_DIR / f"{table_name}_clean.parquet"),
        }
        for table_name, df in cleaned_tables.items()
    ]
).sort("table")

processed_summary

Skipping tickets: ComputeError: parquet: File out of specification: The file must end with PAR1

shape: (5, 4)
┌────────────┬─────────┬─────────┬─────────────────────────────────┐
│ table      ┆ rows    ┆ columns ┆ processed_path                  │
│ ---        ┆ ---     ┆ ---     ┆ ---                             │
│ str        ┆ i64     ┆ i64     ┆ str                             │
╞════════════╪═════════╪═════════╪═════════════════════════════════╡
│ airplanes  ┆ 796     ┆ 13      ┆ c:\Users\rothl\Desktop\ATT Gro… │
│ airports   ┆ 30      ┆ 9       ┆ c:\Users\rothl\Desktop\ATT Gro… │
│ flights    ┆ 1758638 ┆ 10      ┆ c:\Users\rothl\Desktop\ATT Gro… │
│ passengers ┆ 500000  ┆ 11      ┆ c:\Users\rothl\Desktop\ATT Gro… │
│ routes     ┆ 624     ┆ 7       ┆ c:\Users\rothl\Desktop\ATT Gro… │
└────────────┴─────────┴─────────┴─────────────────────────────────┘

### 3.5 Check Cleaned Output

Load the cleaned parquet files and check their null/missing value counts.

In [32]:
processed_table_names = tuple(
    path.name.removesuffix(".parquet")
    for path in sorted(PROCESSED_DIR.glob("*_clean.parquet"))
)

processed_tables = load_tables(
    data_dir=PROCESSED_DIR,
    table_names=processed_table_names,
    skip_errors=True,
)

processed_missing_values = missing_value_counts(processed_tables)
processed_missing_values

shape: (50, 8)
┌─────────────┬─────────────┬─────────┬──────┬────────────┬─────────────┬─────────────┬────────────┐
│ table       ┆ column      ┆ dtype   ┆ rows ┆ null_count ┆ blank_strin ┆ missing_cou ┆ missing_pc │
│ ---         ┆ ---         ┆ ---     ┆ ---  ┆ ---        ┆ g_count     ┆ nt          ┆ t          │
│ str         ┆ str         ┆ str     ┆ i64  ┆ i64        ┆ ---         ┆ ---         ┆ ---        │
│             ┆             ┆         ┆      ┆            ┆ i64         ┆ i64         ┆ f64        │
╞═════════════╪═════════════╪═════════╪══════╪════════════╪═════════════╪═════════════╪════════════╡
│ airplanes_c ┆ seats_premi ┆ Float64 ┆ 796  ┆ 469        ┆ 0           ┆ 469         ┆ 0.589196   │
│ lean        ┆ um          ┆         ┆      ┆            ┆             ┆             ┆            │
│ airplanes_c ┆ seats_busin ┆ Float64 ┆ 796  ┆ 112        ┆ 0           ┆ 112         ┆ 0.140704   │
│ lean        ┆ ess         ┆         ┆      ┆            ┆             ┆             ┆            │
│ airplanes_c ┆ seats_econo ┆ Float64 ┆ 796  ┆ 70         ┆ 0           ┆ 70          ┆ 0.08794    │
│ lean        ┆ my          ┆         ┆      ┆            ┆             ┆             ┆            │
│ airplanes_c ┆ aircraft_re ┆ String  ┆ 796  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0        │
│ lean        ┆ gistration  ┆         ┆      ┆            ┆             ┆             ┆            │
│ airplanes_c ┆ build_date  ┆ Date    ┆ 796  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0        │
│ lean        ┆             ┆         ┆      ┆            ┆             ┆             ┆            │
│ …           ┆ …           ┆ …       ┆ …    ┆ …          ┆ …           ┆ …           ┆ …          │
│ routes_clea ┆ flight_minu ┆ Int64   ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0        │
│ n           ┆ tes         ┆         ┆      ┆            ┆             ┆             ┆            │
│ routes_clea ┆ leg_number  ┆ Int64   ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0        │
│ n           ┆             ┆         ┆      ┆            ┆             ┆             ┆            │
│ routes_clea ┆ origin      ┆ String  ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0        │
│ n           ┆             ┆         ┆      ┆            ┆             ┆             ┆            │
│ routes_clea ┆ parent_rout ┆ String  ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0        │
│ n           ┆ e           ┆         ┆      ┆            ┆             ┆             ┆            │
│ routes_clea ┆ route_code  ┆ String  ┆ 624  ┆ 0          ┆ 0           ┆ 0           ┆ 0.0        │
│ n           ┆             ┆         ┆      ┆            ┆             ┆             ┆            │
└─────────────┴─────────────┴─────────┴──────┴────────────┴─────────────┴─────────────┴────────────┘

## Task 4: Enrich and Model Tables

This section adds simple business features to each table first, then joins the flight-related tables into one analysis-ready master table.

Saving rule for this project:

- save cleaned tables as `*_clean.parquet` checkpoints
- keep enriched intermediate tables in memory
- save the final joined table as `master_flight_dashboard.parquet`

### 4.1 Enrich Each Table

Use the cleaned tables from Task 3 if they are already in memory. Otherwise, read the saved `*_clean.parquet` files from `data/processed`.

In [33]:
if "cleaned_tables" in globals():
    tables_for_enrichment = cleaned_tables
else:
    tables_for_enrichment = {
        path.name.removesuffix("_clean.parquet"): pl.read_parquet(path)
        for path in sorted(PROCESSED_DIR.glob("*_clean.parquet"))
    }

enriched_tables = enrich_tables(
    tables_for_enrichment,
    reference_date=date.today(),
)

enriched_summary = pl.DataFrame(
    [
        {
            "table": table_name,
            "rows": df.height,
            "columns": df.width,
        }
        for table_name, df in enriched_tables.items()
    ]
).sort("table")

enriched_summary

shape: (5, 3)
┌────────────┬─────────┬─────────┐
│ table      ┆ rows    ┆ columns │
│ ---        ┆ ---     ┆ ---     │
│ str        ┆ i64     ┆ i64     │
╞════════════╪═════════╪═════════╡
│ airplanes  ┆ 796     ┆ 17      │
│ airports   ┆ 30      ┆ 12      │
│ flights    ┆ 1758638 ┆ 17      │
│ passengers ┆ 500000  ┆ 14      │
│ routes     ┆ 624     ┆ 11      │
└────────────┴─────────┴─────────┘

### 4.2 Preview Enriched Features

Look at a few new fields that could be useful for a dashboard.

In [34]:
if "flights" in enriched_tables:
    flight_columns = [
        column
        for column in (
            "flight_id",
            "departure_date",
            "departure_hour",
            "is_weekend",
            "scheduled_duration_minutes",
        )
        if column in enriched_tables["flights"].columns
    ]
    display(enriched_tables["flights"].select(flight_columns).head(5))

if "routes" in enriched_tables:
    route_columns = [
        column
        for column in (
            "route_code",
            "distance",
            "distance_band",
            "flight_hours",
            "average_speed",
        )
        if column in enriched_tables["routes"].columns
    ]
    display(enriched_tables["routes"].select(route_columns).head(5))

if "airplanes" in enriched_tables:
    airplane_columns = [
        column
        for column in (
            "aircraft_registration",
            "model",
            "model_family",
            "total_seats",
        )
        if column in enriched_tables["airplanes"].columns
    ]
    display(enriched_tables["airplanes"].select(airplane_columns).head(5))

shape: (5, 5)
┌───────────┬────────────────┬────────────────┬────────────┬────────────────────────────┐
│ flight_id ┆ departure_date ┆ departure_hour ┆ is_weekend ┆ scheduled_duration_minutes │
│ ---       ┆ ---            ┆ ---            ┆ ---        ┆ ---                        │
│ str       ┆ date           ┆ i8             ┆ bool       ┆ i64                        │
╞═══════════╪════════════════╪════════════════╪════════════╪════════════════════════════╡
│ IE0003    ┆ 2010-11-08     ┆ 6              ┆ false      ┆ 46                         │
│ IE0003    ┆ 2010-11-09     ┆ 6              ┆ false      ┆ 46                         │
│ IE0003    ┆ 2010-11-10     ┆ 6              ┆ false      ┆ 46                         │
│ IE0003    ┆ 2010-11-11     ┆ 6              ┆ false      ┆ 46                         │
│ IE0003    ┆ 2010-11-12     ┆ 6              ┆ false      ┆ 46                         │
└───────────┴────────────────┴────────────────┴────────────┴────────────────────────────┘

shape: (5, 5)
┌────────────┬──────────┬───────────────┬──────────────┬───────────────┐
│ route_code ┆ distance ┆ distance_band ┆ flight_hours ┆ average_speed │
│ ---        ┆ ---      ┆ ---           ┆ ---          ┆ ---           │
│ str        ┆ i64      ┆ str           ┆ f64          ┆ f64           │
╞════════════╪══════════╪═══════════════╪══════════════╪═══════════════╡
│ R001       ┆ 1621     ┆ medium        ┆ 2.25         ┆ 720.4         │
│ R002       ┆ 655      ┆ short         ┆ 1.1          ┆ 595.5         │
│ R003       ┆ 1223     ┆ short         ┆ 1.783333     ┆ 685.8         │
│ R004       ┆ 3613     ┆ medium        ┆ 4.633333     ┆ 779.8         │
│ R005       ┆ 2807     ┆ medium        ┆ 3.666667     ┆ 765.5         │
└────────────┴──────────┴───────────────┴──────────────┴───────────────┘

shape: (5, 4)
┌───────────────────────┬──────────────────────┬──────────────┬─────────────┐
│ aircraft_registration ┆ model                ┆ model_family ┆ total_seats │
│ ---                   ┆ ---                  ┆ ---          ┆ ---         │
│ str                   ┆ str                  ┆ str          ┆ f64         │
╞═══════════════════════╪══════════════════════╪══════════════╪═════════════╡
│ IE53571               ┆ BOMBARDIER CRJ-1000  ┆ Other        ┆ 100.0       │
│ IE53730               ┆ BOMBARDIER CRJ-900   ┆ Other        ┆ 90.0        │
│ IE53994               ┆ AIRBUS A321-200(321) ┆ Airbus       ┆ 212.0       │
│ IE54017               ┆ AIRBUS A350-900(359) ┆ Airbus       ┆ 348.0       │
│ IE54199               ┆ AIRBUS A330-200(332) ┆ Airbus       ┆ 314.0       │
└───────────────────────┴──────────────────────┴──────────────┴─────────────┘

### 4.3 Join Tables, Verify Row Counts, and Save Master

Build one flight-level dashboard table by joining flights to routes, airplanes, and origin/destination airports. Then check that the joins did not unexpectedly add or lose rows.

This master table does not include `tickets` yet because the tickets parquet file is corrupted. It also does not include passenger fields yet, because passengers connect to flights through tickets.

In [35]:
required_join_tables = {"flights", "routes", "airplanes", "airports"}
missing_join_tables = required_join_tables - set(enriched_tables)

if missing_join_tables:
    print(f"Missing tables for flight dashboard join: {sorted(missing_join_tables)}")
else:
    master_flight_dashboard = make_flight_dashboard_table(
        enriched_tables["flights"],
        enriched_tables["routes"],
        enriched_tables["airplanes"],
        enriched_tables["airports"],
    )

    join_checks = check_flight_dashboard_joins(
        enriched_tables["flights"],
        enriched_tables["routes"],
        enriched_tables["airplanes"],
        enriched_tables["airports"],
        master_flight_dashboard,
    )

    master_table_path = PROCESSED_DIR / "master_flight_dashboard.parquet"
    master_flight_dashboard.write_parquet(master_table_path)

    display(join_checks)

    print(f"Flight rows before join: {enriched_tables['flights'].height:,}")
    print(f"Master dashboard rows after join: {master_flight_dashboard.height:,}")
    print(f"Saved master table to: {master_table_path}")

shape: (5, 7)
┌──────────────┬───────────┬─────────────┬──────────────┬──────────────┬─────────────┬─────────────┐
│ join         ┆ left_rows ┆ joined_rows ┆ unmatched_ro ┆ duplicate_ri ┆ row_count_o ┆ all_keys_ma │
│ ---          ┆ ---       ┆ ---         ┆ ws           ┆ ght_keys     ┆ k           ┆ tched       │
│ str          ┆ i64       ┆ i64         ┆ ---          ┆ ---          ┆ ---         ┆ ---         │
│              ┆           ┆             ┆ i64          ┆ i64          ┆ bool        ┆ bool        │
╞══════════════╪═══════════╪═════════════╪══════════════╪══════════════╪═════════════╪═════════════╡
│ flights to   ┆ 1758638   ┆ 1758638     ┆ 0            ┆ 0            ┆ true        ┆ true        │
│ routes       ┆           ┆             ┆              ┆              ┆             ┆             │
│ flights to   ┆ 1758638   ┆ 1758638     ┆ 0            ┆ 0            ┆ true        ┆ true        │
│ airplanes    ┆           ┆             ┆              ┆              ┆             ┆             │
│ routes to    ┆ 624       ┆ 624         ┆ 0            ┆ 0            ┆ true        ┆ true        │
│ origin       ┆           ┆             ┆              ┆              ┆             ┆             │
│ airports     ┆           ┆             ┆              ┆              ┆             ┆             │
│ routes to    ┆ 624       ┆ 624         ┆ 0            ┆ 0            ┆ true        ┆ true        │
│ destination  ┆           ┆             ┆              ┆              ┆             ┆             │
│ airports     ┆           ┆             ┆              ┆              ┆             ┆             │
│ final flight ┆ 1758638   ┆ 1758638     ┆ null         ┆ null         ┆ true        ┆ null        │
│ dashboard    ┆           ┆             ┆              ┆              ┆             ┆             │
│ table        ┆           ┆             ┆              ┆              ┆             ┆             │
└──────────────┴───────────┴─────────────┴──────────────┴──────────────┴─────────────┴─────────────┘

Flight rows before join: 1,758,638
Master dashboard rows after join: 1,758,638
Saved master table to: c:\Users\rothl\Desktop\ATT Group Project\ATT-Group8\data\processed\master_flight_dashboard.parquet

In [36]:
master_path = PROCESSED_DIR / "master_flight_dashboard.parquet"

if "master_flight_dashboard" not in globals():
    master_flight_dashboard = pl.read_parquet(master_path)

display(master_flight_dashboard.head(10))

shape: (10, 71)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ flight_id ┆ flight_le ┆ frequency ┆ route_cod ┆ … ┆ destinati ┆ destinati ┆ is_domest ┆ is_same_ │
│ ---       ┆ g         ┆ ---       ┆ e         ┆   ┆ on_has_co ┆ on_airpor ┆ ic_route  ┆ continen │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ordinates ┆ t_tax_ban ┆ ---       ┆ t_route  │
│           ┆ i64       ┆           ┆ str       ┆   ┆ ---       ┆ d         ┆ bool      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ ---       ┆           ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
│ IE0003    ┆ 0         ┆ F1        ┆ R235      ┆ … ┆ true      ┆ low       ┆ true      ┆ true     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘